function add() {
    numb++;
    if (numb == 7){
        numb = 1
    }
    let day = days[numb];
    h1.innerHTML = '<h1>'+day+'</h1>';
}
function sub() {
    numb--;
    if (numb == 0){
        numb = 6;
    }
    let day = days[numb];
    h1.innerHTML = '<h1>'+day+'</h1>';
}
plus.addEventListener('click', add);
mins.addEventListener('click', sub);
let cookies = document.cookie.split(';');
function save() {
    var tahi1 = document.getElementById("tahi1").value;
    document.cookie = "tahi1 =" + tahi1 + ";";
    var rua1 = document.getElementById("rua1").value;
    document.cookie = "rua1 =" + rua1 + ";";
    var toru1 = document.getElementById("toru1").value;
    document.cookie = "toru1 =" + toru1 + ";";
    var wha1 = document.getElementById("wha1").value;
    document.cookie = "wha1 =" + wha1 + ";";
    var rima1 = document.getElementById("rima1").value;
    document.cookie = "rima1 =" + rima1 + ";";
    var ono1 = document.getElementById("ono1").value;
    document.cookie = "ono1 =" + ono1 + ";";
    var tahi2 = document.getElementById("tahi2").value;
    document.cookie = "tahi2 =" + tahi2 + ";";
    var rua2 = document.getElementById("rua2").value;
    document.cookie = "rua2 =" + rua2 + ";";
    var toru2 = document.getElementById("toru2").value;
    document.cookie = "toru2 =" + toru2 + ";";
    var wha2 = document.getElementById("wha2").value;
    document.cookie = "wha2 =" + wha2 + ";";
    var rima2 = document.getElementById("rima2").value;
    document.cookie = "rima2 =" + rima2 + ";";
    var ono2 = document.getElementById("ono2").value;
    document.cookie = "ono2 =" + ono2 + ";";
    var tahi3 = document.getElementById("tahi3").value;
    document.cookie = "tahi3 =" + tahi3 + ";";
    var rua3 = document.getElementById("rua3").value;
    document.cookie = "rua3 =" + rua3 + ";";
    var toru3 = document.getElementById("toru3").value;
    document.cookie = "toru3 =" + toru3 + ";";
    var wha3 = document.getElementById("wha3").value;
    document.cookie = "wha3 =" + wha3 + ";";
    var rima3 = document.getElementById("rima3").value;
    document.cookie = "rima3 =" + rima3 + ";";
    var ono3 = document.getElementById("ono3").value;
    document.cookie = "ono3 =" + ono3 + ";";
    var tahi4 = document.getElementById("tahi4").value;
    document.cookie = "tahi4 =" + tahi4 + ";";
    var rua4 = document.getElementById("rua4").value;
    document.cookie = "rua4 =" + rua4 + ";";
    var toru4 = document.getElementById("toru4").value;
    document.cookie = "toru4 =" + toru4 + ";";
    var wha4 = document.getElementById("wha4").value;
    document.cookie = "wha4 =" + wha4 + ";";
    var rima4 = document.getElementById("rima4").value;
    document.cookie = "rima4 =" + rima4 + ";";
    var ono4 = document.getElementById("ono4").value;
    document.cookie = "ono4 =" + ono4 + ";";
    var tahi5 = document.getElementById("tahi5").value;
    document.cookie = "tahi5 =" + tahi5 + ";";
    var rua5 = document.getElementById("rua5").value;
    document.cookie = "rua5 =" + rua5 + ";";
    var toru5 = document.getElementById("toru5").value;
    document.cookie = "toru5 =" + toru5 + ";";
    var wha5 = document.getElementById("wha5").value;
    document.cookie = "wha5 =" + wha5 + ";";
    var rima5 = document.getElementById("rima5").value;
    document.cookie = "rima5 =" + rima5 + ";";
    var ono5 = document.getElementById("ono5").value;
    document.cookie = "ono5 =" + ono5 + ";";
}
let cookies0 = cookies[0].replace("tahi1=","");
document.getElementById('tahi1').value = cookies0;
let cookies1 = cookies[1].replace("rua1=","");
let cookie1 = cookies1.replace(" ","");
document.getElementById('rua1').value = cookie1;
let cookies2 = cookies[2].replace("toru1=","");
let cookie2 = cookies2.replace(" ","");
document.getElementById('toru1').value = cookie2;
let cookies3 = cookies[3].replace("wha1=","");
let cookie3 = cookies3.replace(" ","");
document.getElementById('wha1').value = cookie3;
let cookies4 = cookies[4].replace("rima1=","");
let cookie4 = cookies4.replace(" ","");
document.getElementById('rima1').value = cookie4;
let cookies5 = cookies[5].replace("ono1=","");
let cookie5 = cookies5.replace(" ","");
document.getElementById('ono1').value = cookie5;
let cookies6 = cookies[6].replace("tahi2=","");
let cookie6 = cookies6.replace(" ","");
document.getElementById('tahi2').value = cookie6;
let cookies7 = cookies[7].replace("rua2=","");
let cookie7 = cookies7.replace(" ","");
document.getElementById('rua2').value = cookie7;
let cookies8 = cookies[8].replace("toru2=","");
let cookie8 = cookies8.replace(" ","");
document.getElementById('toru2').value = cookie8;
let cookies9 = cookies[9].replace("wha2=","");
let cookie9 = cookies9.replace(" ","");
document.getElementById('wha2').value = cookie9;
let cookies10 = cookies[10].replace("rima2=","");
let cookie10 = cookies10.replace(" ","");
document.getElementById('rima2').value = cookie10;
let cookies11 = cookies[11].replace("ono2=","");
let cookie11 = cookies11.replace(" ","");
document.getElementById('ono2').value = cookie11;
let cookies12 = cookies[12].replace("tahi3=","");
let cookie12 = cookies12.replace(" ","");
document.getElementById('tahi3').value = cookie12;
let cookies13 = cookies[13].replace("rua3=","");
let cookie13 = cookies13.replace(" ","");
document.getElementById('rua3').value = cookie13;
let cookies14 = cookies[14].replace("toru3=","");
let cookie14 = cookies14.replace(" ","");
document.getElementById('toru3').value = cookie14;
let cookies15 = cookies[15].replace("wha3=","");
let cookie15 = cookies15.replace(" ","");
document.getElementById('wha3').value = cookie15;
let cookies16 = cookies[16].replace("rima3=","");
let cookie16 = cookies16.replace(" ","");
document.getElementById('rima3').value = cookie16;
let cookies17 = cookies[17].replace("ono3=","");
let cookie17 = cookies17.replace(" ","");
document.getElementById('ono3').value = cookie17;
let cookies18 = cookies[18].replace("tahi4=","");
let cookie18 = cookies18.replace(" ","");
document.getElementById('tahi4').value = cookie18;
let cookies19 = cookies[19].replace("rua4=","");
let cookie19 = cookies19.replace(" ","");
document.getElementById('rua4').value = cookie19;
let cookies20 = cookies[20].replace("toru4=","");
let cookie20 = cookies20.replace(" ","");
document.getElementById('toru4').value = cookie20;
let cookies21 = cookies[21].replace("wha4=","");
let cookie21 = cookies21.replace(" ","");
document.getElementById('wha4').value = cookie21;
let cookies22 = cookies[22].replace("rima4=","");
let cookie22 = cookies22.replace(" ","");
document.getElementById('rima4').value = cookie22;
let cookies23 = cookies[23].replace("ono4=","");
let cookie23 = cookies23.replace(" ","");
document.getElementById('ono4').value = cookie23;
let cookies24 = cookies[24].replace("tahi5=","");
let cookie24 = cookies24.replace(" ","");
document.getElementById('tahi5').value = cookie24;
let cookies25 = cookies[25].replace("rua5=","");
let cookie25 = cookies25.replace(" ","");
document.getElementById('rua5').value = cookie25;
let cookies26 = cookies[26].replace("toru5=","");
let cookie26 = cookies26.replace(" ","");
document.getElementById('toru5').value = cookie26;
let cookies27 = cookies[27].replace("wha5=","");
let cookie27 = cookies27.replace(" ","");
document.getElementById('wha5').value = cookie27;
let cookies28 = cookies[28].replace("rima5=","");
let cookie28 = cookies28.replace(" ","");
document.getElementById('rima5').value = cookie28;
let cookies29 = cookies[29].replace("ono5=","");
let cookie29 = cookies29.replace(" ","");
document.getElementById('ono5').value = cookie29;
